version: '3.6'
services:
    localsalt:
        build: './'
        image: localsalt
        links:
        - mysql56
        ports:
        - "80:80"
        - "81:81"
        - "443:443"
        - "3000:3000"
        - "3001:3001"
        - "4200:4200"
        volumes:
        - "../salt_crm:/opt/www/salt-old/race_custom/salt_crm"
        - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
        environment:
        - DB_HOST=mysql56
        - PHP_MEMORY_LIMIT=128M

    mysql56:
        image: mysql:5.6
        ports:
        - "3306:3306"
        volumes:
        - "../mysql56-data:/var/lib/mysql"
        environment:
        - MYSQL_ROOT_PASSWORD=123456 # mật khẩu root user

    phpmyadmin:
        depends_on:
        - mysql56
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - '8080:80'
        environment:
        - PMA_HOST=mysql56
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=123456
