version: '3.6'
services:
    localsalt:
        build: './centos-apache-php'
        image: localsalt
        links:
        - mysql56
        ports:
        - ${APP_PORT}:80
        - ${APP_SSL_PORT}:443
        volumes:
        - ${SOURCE_PATH}:${VOLUME_PATH}
        - ${HOST_CONF_PATH}:/opt/docker/etc/httpd/vhost.conf
        environment:
        - DB_HOST=mysql56
        - PHP_MEMORY_LIMIT=128M

    mysql56:
        image: mysql:5.6
        ports:
        - ${MYSQL_PORT}:3306
        volumes:
        - ${MYSQL_DATA}:/var/lib/mysql
        environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=123456 # mật khẩu root user