version: '3.6'
services:
    saltold:
        build: './centos-apache-php'
        image: salt-old
        links:
        - mysql56
        ports:
        - ${APP_OLD_PORT}:80
        volumes:
        - ${SOURCE_OLD_PATH}:${VOLUME_OLD_PATH}
        - ./apache/vhost-old.conf:/opt/docker/etc/httpd/vhost.conf
        environment:
        - DB_HOST=mysql56
        - PHP_MEMORY_LIMIT=128M

    saltnew:
        build: './centos-apache-php'
        image: salt-new
        links:
        - mysql56
        ports:
        - ${APP_NEW_PORT}:80
        volumes:
        - ${SOURCE_NEW_PATH}:${VOLUME_NEW_PATH}
        - ./apache/vhost-new.conf:/opt/docker/etc/httpd/vhost.conf
        environment:
        - DB_HOST=mysql56
        - PHP_MEMORY_LIMIT=128M
    
    mysql56:
        image: mysql:5.6
        ports:
        - ${MYSQL_PORT}:3306
        volumes:
        - ${MYSQL_DATA}:/var/lib/mysql
        environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=123456 # mật khẩu root user